name: Genshin Data Spider
on:
  schedule:
    - cron: '0 4 */4 * *'
  workflow_dispatch:
jobs:
  spider:
    runs-on: ubuntu-latest
    name: "Scrape Genshin Data"
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Setup Python
        uses: actions/setup-python@v4.7.0
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install --upgrade poetry
          poetry config virtualenvs.create false
          poetry install

      - name: Run Spider
        run: python -m run.py

      - name: Commit and push
        run: |-
          git config --global user.email "bot@github.com" && git config --global user.name "Waka-Bot"
          git diff
          git add ./out && git commit -m ":memo: update profile" || exit 0
          git pull && git push
